# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Java CI com Maven

# Gatilho: Roda em todo push ou pull request para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define os trabalhos (jobs) a serem executados
jobs:
  build-e-test:
    # Roda em uma máquina virtual Ubuntu fornecida pelo GitHub
    runs-on: ubuntu-latest

    # Define os passos sequenciais do trabalho
    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente com Java JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Executa os testes com Maven
      - name: Rodar testes com Maven
        run: mvn test
